### ISSUE TITLE
cannot generate index.ts for enum types

### ISSUE THREAD

**Issue by raphaelsoul** [imjuni/ctix#1]
I've found enum types are ignored when creating index.ts
A complete reproduce repo here
https://github.com/raphaelsoul/ctix-reproducable

step for  reproduce: run `npm run generate`

Issue 1: `src/enums/index.ts` is not generated
Issue 2: `src/models/index.ts` not contains `export * from './another.user.enums`

![image](https://user-images.githubusercontent.com/8615787/104434010-b0ea5e80-55c5-11eb-9b58-130044ac02c2.png)

Any Ideas against this?

**Comment by imjuni** [comment]
@raphaelsoul Hi,

Thank you for your feedback.

I fix this issue include export default.

Thank you!
