### ISSUE TITLE
Support specifying file extension

### ISSUE THREAD

**Issue by jovinbm** [imjuni/ctix#131]
Hi,

First of all, thank you for the library. I'm in the process of migrating a project to ESM which requires a `.js` extension ([see here](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-move-my-commonjs-project-to-esm)) even in typescript. Is there a way to specify that the file extension should be compiled from `.ts` to `.tsx` and from `.tsx` to `.jsx`.

I see that there is a `fileExt` option in config but it is pretty limited in what it allows.

Thank you.

**Comment by imjuni** [comment]
Hi, 

Thank you for feedback. When using ctix in an ESM project, if I set the fileExt option to `to-js`, it changes it either to `.js` or `.jsx`. The [`getImportStatementReplaceJs`](https://github.com/imjuni/ctix/blob/master/src/modules/path/getImportStatementReplaceJs.ts) function makes this change. Is there a case where I need to make a more detailed change than the `getImportStatementReplaceJs` function? It would be useful if you could create a reproducible repo to show it to me so I can modify it. Thank you!

**Comment by jovinbm** [comment]
Oh, I did not know about `to-js`. That is exactly what I needed. Thank you
