### ISSUE TITLE
[Feature] Option to change default exports aliasing

### ISSUE THREAD

**Issue by ggondim** [imjuni/ctix#14]
I needed my default exported modules to be exported with their original file name, instead an alias with the full file path.

```typescript
// instead original ctix:
export { default as srcPathToMyModule } from './src/path/to/MyModule';

// changes to:
export { default as MyModule } from './src/path/to/MyModule';
```

I made a quick fork and adapted it for me in [ggondim/ctix](https://github.com/ggondim/ctix).

Please consider adding an option to export defaults as their original file name or some alias formatting option.

**Comment by imjuni** [comment]
@ggondim Hi, 

Thank you for your feedback. But I think your suggestion raise error some case. 

* src
    * typescript/write.ts
    * javascript/write.ts

In this case, ctix create same module name after that raise error.

I consider support additional option.

**Comment by imjuni** [comment]
@ggondim Hi,

I add `excludePath` and `useUpperFirst` option. This option work your want it. 

Thank you!

**Comment by ggondim** [comment]
It's working, thank you very much!
