### ISSUE TITLE
Can't exclude `@ctix-declaration` file

### ISSUE THREAD

**Issue by smallmain** [imjuni/ctix#154]
[ctix-demo.zip](https://github.com/user-attachments/files/16598951/ctix-demo.zip)

Please check the project:

- `exclulde: ["**check**"]`
- file `check.ts` not excluded
- file `check2.ts` has excluded

**Comment by imjuni** [comment]
@smallmain Hi, 

I believe the glob pattern needs to be changed. The `**check**` glob pattern does not work as intended. Please refer to the [link](https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2A%2Acheck%2A%2A&matches=false&tests=%2F%2F%20This%20will%20match%20as%20it%20ends%20with%20%27.js%27&tests=check.ts&tests=%2F%2F%20This%20won%27t%20match%21&tests=check2.ts) below and update the glob pattern accordingly.

**Comment by smallmain** [comment]
Hi, I clicked the link below, but I still don't understand what's wrong with glob pattern.

![CleanShot 2024-08-19 at 09 16 34@2x](https://github.com/user-attachments/assets/9bcdbed0-aa20-48b7-af5f-d6cfe7517114)

**Comment by imjuni** [comment]
The exclude configuration now runs before the comment directive. In version 2.6.1, the comment directive had higher priority than the exclude option. This was changed in version 2.6.2.
