### ISSUE TITLE
Error when using programming interface

### ISSUE THREAD

**Issue by smallmain** [imjuni/ctix#155]
```
file:///Users/smallmain/Documents/Work/xenon-studio/misc/node_modules/.pnpm/ctix@2.6.1_prettier-plugin-organize-imports@3.2.4_prettier@3.3.3_typescript@5.5.4__prettier@3.3.3_typescript@5.5.4/node_modules/ctix/dist/esm/index.mjs:3929
import { CheckboxPlusPrompt } from "inquirer-ts-checkbox-plus-prompt";
         ^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'CheckboxPlusPrompt' not found. The requested module 'inquirer-ts-checkbox-plus-prompt' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'inquirer-ts-checkbox-plus-prompt';
const { CheckboxPlusPrompt } = pkg;
```

Environment:

- Node.js v20
- MacOS 14.5(ARM)

[ctix-demo.zip](https://github.com/user-attachments/files/16599067/ctix-demo.zip)

Run `node ./cli.js` will reproduce the error.

**Comment by imjuni** [comment]
Unfortunately, the chalk and inquirer packages only support CommonJS, so they cannot run ESM scripts. If ctix switches to ESM, it will solve this problem, but in that case, ctix will no longer work in CommonJS environments. Therefore, I am considering the right timing for ESM support.

The scripts below are working fine in the CommonJS format.

```js
// rename file: cli.js > cli.cjs

const { building, parseConfig } = require("ctix");
const { readFileSync } = require("fs");
const options = readFileSync(".ctirc");

// output field is required
options.output = '.';

building(parseConfig(options));
```

**Comment by imjuni** [comment]
This issue cannot be resolved by calling CJS within an MJS script. You need to run pure CJS, as shown in the attached file.

```js
const { building, parseConfig } = require("ctix");
const { readFileSync } = require("fs");
const option = parseConfig(readFileSync(".ctirc"));
// or add output configuration in .ctirc
const withOption = {
  ...option,
  options: option.options.map((o) => ({ ...o, output: "." })),
};

building(withOption);
```

[cli.cjs.zip](https://github.com/user-attachments/files/16665011/cli.cjs.zip)

**Comment by smallmain** [comment]
> This issue cannot be resolved by calling CJS within an MJS script. You need to run pure CJS, as shown in the attached file.
> 
> ```js
> const { building, parseConfig } = require("ctix");
> const { readFileSync } = require("fs");
> const option = parseConfig(readFileSync(".ctirc"));
> // or add output configuration in .ctirc
> const withOption = {
>   ...option,
>   options: option.options.map((o) => ({ ...o, output: "." })),
> };
> 
> building(withOption);
> ```
> 
> [cli.cjs.zip](https://github.com/user-attachments/files/16665011/cli.cjs.zip)

Thank you for the explanation.
