### ISSUE TITLE
Parameters are overwritten

### ISSUE THREAD

**Issue by DawnKing** [imjuni/ctix#19]
I use cli command: 
npx ctix create --project="./tsconfig.json" --useBackupFile=false  --quote='\"' 

And params always don't take effect.Then i find getMergedConfig() parentOptions be overwrite.Here are logs

optionObject
{"dir":"D:\\Ts\\libs","exists":false,"depth":1}

parentOptions
{"addNewline":true,"useSemicolon":true,"useTimestamp":false,"useComment":true,"exportFilename":"index.ts","quote":"\"","verbose":false,"useBackupFile":false,"output":"D:\\Ts\\tsconfig.json","useRoot
Dir":false,"excludePath":false,"useUpperFirst":true,"project":"./tsconfig.json"}

newOptionObject
{"dir":"D:\\Ts\\libs","exists":false,"depth":1,"option":{"addNewline":true,"useSemicolon":true,"useTimestamp":false,"useComment":true,"exportFilename":"index.ts","quote":"'","verbose":false,"useBack
upFile":true,"output":"./tsconfig.json","useRootDir":false,"excludePath":false,"useUpperFirst":true,"project":"./tsconfig.json"}}

**Comment by imjuni** [comment]
@DawnKing Hi,

ctix goal can support different option in subdirectory. So merge order is right. If change order, parent option overwrite timestamp and comment, quote option. 

You can create error example your repository? I see example, after I consider that problem.

Thank you!

**Comment by DawnKing** [comment]
@imjuni Hello,
There is my example.
https://github.com/DawnKing/ctix/tree/type05/example/type05

There is my command
D:\ctix\example\type05>npx ctix create --project="./tsconfig.json" --useBackupFile=false --quote='"'

1. I want double quotation marks.
2. I don't use backup file.
3. The sub1 directory not generate index.ts.

Thanks!

**Comment by imjuni** [comment]
@DawnKing Hi,

I fix this issue 0.6.0 version. Thank you for your feedback!

**Comment by DawnKing** [comment]
@imjuni 
Hi, 
If there are no scripts in the folder, index.ts will not be generated.
Can you fix the problem?

There is my example. The sub1 directory not generate index.ts.
https://github.com/DawnKing/ctix/tree/type05/example/type05

![image](https://github.com/DawnKing/ctix/blob/type05/example/type05/1.PNG)


Thanks!
