### ISSUE TITLE
Fix dependency to vulnerable merge 1.2.1 

### ISSUE THREAD

**Issue by gmuehlenberg** [imjuni/ctix#2]
Hello, thank you for the ctix lib! It's doing a great job and saving me a lot of trouble. Only one problem:

The dependency to `merge ^1.2.1` should be raised to `^2.1.1` at least to fix a security vulnerability.
![image](https://user-images.githubusercontent.com/28754391/120277024-c7166400-c2b3-11eb-9f4f-6b4a786b75b5.png)

more info:  https://npmjs.com/advisories/1666

**Comment by imjuni** [comment]
@gmuehlenberg Hi,

I fix this issue,

Thank you.
