### ISSUE TITLE
How to exclude __tests__ folders?

### ISSUE THREAD

**Issue by F7502** [imjuni/ctix#22]
Hello,

I am able to successfully generate an `index.ts` file but this also contains entries like this;
```
export * from "./__tests__/some/path";
```

How do I exclude test folders from being added to the index?

Thanks in advance :-)

**Comment by imjuni** [comment]
@F7502 Hi,

You have 3 option.

1. add .gitignore
2. add .npmignore
3. create new tsconfig.json (ex> tsconfig.ctix.json) after set exclude option you want

**Comment by F7502** [comment]
Many thanks, option 3 fits well for my use case.
