### ISSUE TITLE
ctix single should output to `rootDir` when it exists rather than root of project

### ISSUE THREAD

**Issue by insidewhy** [imjuni/ctix#3]
When my tsconfig.json has `rootDir: "src"`, then `ctix single -p tsconfig.json` should output the `index.ts` as `src/index.ts` (with imports relative to `src`) rather than next to `tsconfig.json`. Using `yarn ctix single -p tsconfig.json -f src/index.ts` doesn't help because the imports in `src/index.ts` are still relative to the root directory rather than `src`.

**Comment by imjuni** [comment]
@insidewhy Hi, 

I think that ctix configuration is different tsconfig.json. tsconfig.json file need for detect typescript source file and compile options. But don't need rootDir, paths, etc.

So I think this feature increase complexity, but I understand need (developer decide rootDir, after it write in tsconfig.json. So auto generated source file create at rootDir. That is reasonable)

But I think this feature add by option isn't default. How about it?

**Comment by insidewhy** [comment]
@imjuni Sure

**Comment by imjuni** [comment]
@insidewhy Hi,

I add useRootDir option in 0.4.0 version. Thank you.
