### ISSUE TITLE
Re-exporting a type should consider about 'isolatedModules' flag

### ISSUE THREAD

**Issue by KotoriK** [imjuni/ctix#33]
## Current Behaviour
Current version of ```ctix``` will re-export a default exported type using this schema:
```ts
//in T.ts
type T = string;
export default T;
```
```ts
//in index.ts generated by ctix
export { default as T} from './T';
```
which will encounter following compile error when  '--isolatedModules' flag is set: 

```
TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
```
## Motivation
Since '--isolatedModules' flag is required by powerful typescript compilers (```esbuild``` for example), it will be great to consider about 'isolatedModules'.
## Reference
[Typescript Handbook](https://www.typescriptlang.org/tsconfig#isolatedModules)

**Comment by imjuni** [comment]
@KotoriK Hi,

I agree importance of isolatedModules option! 

But I need a some time because how can determine `export type` or `export` in ctix.

I will try to found everyone understandable and agree soludtion.

Thank you!

**Comment by imjuni** [comment]
@KotoriK Hi,

ctix support isolatedModules option version after 1.2.2

Thank you :)
