### ISSUE TITLE
module.exports fails

### ISSUE THREAD

**Issue by iskhakovt** [imjuni/ctix#37]
Example:

```
a = {}
a.b = {}
a.b.c = {}
a.b.c.X = function () {}

module.exports = a.b.c;
```

results with `ERROR  Cannot support type: (206) a.b.c.X`.

An export like the above is produced by protoc-gen-grpc-web.

**Comment by imjuni** [comment]
@iskhakovt Hi,

If you execute JavaScript? ctix use TypeScript parser api, So can't support JavaScript.

Thank you
