### ISSUE TITLE
index.ts is not created 

### ISSUE THREAD

**Issue by iDschepe** [imjuni/ctix#4]
Hi @imjuni, 

I try to get this tool running in my project.
Great idea btw! I like it very much! 👍

Unfortunately I have problems generating any index.ts file at all.
Both modes, create and single aren't generating any index file. 

The following setup won't work (current version 0.3.3): 
![image](https://user-images.githubusercontent.com/40547587/146833681-64e089e8-eab8-48fd-be91-5bd64109d2be.png)

I also checked out locally ctix-reproducable-master at https://github.com/raphaelsoul/ctix-reproducable 
Updated ctix to 0.3.3:
Here I can generate index.ts files, even with copied tsconfig.json from my project.

Is there a bug, or do I miss some configuration? Maybe you got some hints.

Thanks and best regards!
iDschepe

**Comment by imjuni** [comment]
@iDschepe Hi,

Thank you for ctix using. 

I check about your [ctix-reproducable](https://github.com/raphaelsoul/ctix-reproducable).

ctix 0.3.1 have some bug, sorry update 0.4.1.

0.3.x have a bug that cannot extract enum. I fix this bug in 0.4.x.

Thank you!
