### ISSUE TITLE
ctix not creating root index.ts

### ISSUE THREAD

**Issue by sirpy** [imjuni/ctix#44]
I have a project with different folders under "src"
`ctix create` successfully creates the index.ts file for all folders
except for the index.ts of the root "src" folder that should export all of the other files.
running `ctix single` seems to work fine and it creates the index.ts file

on another project i had to put a dummy file with `export {}` in the "src" folder which then caused ctix to create the index file correctly, but for this project it doesnt help

**Comment by imjuni** [comment]
@sirpy Hi,

I think that your problem raise cause from skipEmptyDir option. 

See skipEmptyDir option at [docs](https://imjuni.github.io/ctix/usage/create-command.html#in-case-of-skipemptydir-value-true)

**Comment by sirpy** [comment]
@imjuni i tried that already no help

**Comment by imjuni** [comment]
@sirpy Hi,

I add new option startAt on #50, use new option [`startAt`](https://imjuni.github.io/ctix/usage/create-command.html#startat-mechanishm).

Thank you!
