### ISSUE TITLE
`getIsIsolatedModules` calculation depends on the order of the exported declarations

### ISSUE THREAD

**Issue by dankeboy36** [imjuni/ctix#52]
Thank you for the great lib!

I noticed that the `isIsolatedModules` evaluation depends on the order of the export declarations. I am using partial ignores.

Setup:

`./src/Foo.ts`:
```ts
export const Foo = { foo: 'foo' } as const;
export type Foo = typeof Foo;

export interface Ignore {}
```

`./src/Bar.ts`:
```ts
export type Bar = typeof Bar;
export const Bar = { bar: 'bar' } as const;

export interface Ignore {}
```

`.ctiignore`:
```json
{
    "**/*.ts": [
        "Ignore"
    ]
}
```

Generated `./src/index.ts`:
```ts
export { type Bar } from './bar';
export { Foo } from './foo';

```

Expected output `./src/index.ts`:
```ts
export { Bar } from './bar';
export { Foo } from './foo';
```

I see that the following `ExportedDeclarations` is evaluated as `TypeAliasDeclaration`, so it's considered an isolated module and gets the `type` export.
```ts
'export type Bar = typeof Bar;'
```

https://github.com/imjuni/ctix/blob/47e743e733cc6e7887c5a41905cda1ddaf217cbc/src/compilers/getIsIsolatedModules.ts#L27-L29

The following `ExportedDeclarations` is a `VariableDeclaration`. Hence it evaluates to `false` and `type` is **not** generated for the export.
```ts
' Foo = { foo: 'foo' } as const'
```

https://github.com/imjuni/ctix/blob/47e743e733cc6e7887c5a41905cda1ddaf217cbc/src/compilers/getIsIsolatedModules.ts#L11-L13

It would be great if the export could be deterministic and consider the same names in the scope. I am generating the code and have no control over the order.

I am happy to create a repo if needed. Thank you!

**Comment by imjuni** [comment]
@dankeboy36 Thank you for your awesome contribution!

If you use partial ignore, ctix generate source code like that 

```
export { type Bar } from './bar';
export { type Foo } from './foo';
```
Compilation failure occurs if the developer has enabled the [isolatedModules](https://www.typescriptlang.org/tsconfig/#isolatedModules) option (include [me](https://github.com/imjuni/jin-frame/blob/master/tsconfig.json)). #33 issue discuss about this option.

If there is no problem with this change, I will review and release the new version

**Comment by dankeboy36** [comment]
I appreciate your time!

> ctix have to generate source code like that

The above example proves that the generation depends on the declaration order.

> Because compilation failure occurs if the developer has enabled the [isolatedModules](https://www.typescriptlang.org/tsconfig/#isolatedModules) option (include [me](https://github.com/imjuni/jin-frame/blob/master/tsconfig.json)). #33 issue discuss about this option.

Sure, I got it. With the proposed changes, the current logic should not change for the currently supported `SyntaxKind`s if there is no name collision among the exported declarations. If there is, the PR should correct the logic and make the index generator deterministic.

As I [mentioned](https://github.com/imjuni/ctix/pull/54#issuecomment-1252551446) on the PR, I am happy to add tests if you can give me some assistance. 😊 Thank you!

**Comment by dankeboy36** [comment]
Could you please release a new version with the changes, @imjuni? Thank you!

**Comment by imjuni** [comment]
@dankeboy36 Hi,

I release [1.5.0](https://github.com/imjuni/ctix/releases/tag/v1.5.0), include your PR. 

Thank you for your contribution! 👍
