### ISSUE TITLE
--ignoreFile option not working

### ISSUE THREAD

**Issue by insidewhy** [imjuni/ctix#55]
I'm using the following command because I need to generate two indexes, one for browsers and one for node:

```bash
gen-commonjs-index": "ctix single -w -p tsconfig.json -o . --ignoreFile .ctiignore-commonjs -f commonjs-index.ts
```

But it's still using `.ctiignore` as the ignore file.

**Comment by imjuni** [comment]
@insidewhy Hi,

I enhance argument processing mechanism.

Please retry v1.5.0.

Thank you :)
