### ISSUE TITLE
export default HoC's are not supported

### ISSUE THREAD

**Issue by L03TJ3** [imjuni/ctix#58]
As title states, exporting a HoC directly as unnamed default fails to compile with error:
```[22-10-25 23:17:38] error: Cannot support type: (208) withTheme()(TestComponent)```
```[22-10-25 23:17:38] error: Error: Cannot support type: (208) withTheme()(TestComponent)```

Is it a configuration thing, or does something need to be fixed on the back-end in order to support this
Basic minified example repo:
https://github.com/L03TJ3/Sample_ExportHOC

Thanks!

**Comment by imjuni** [comment]
@L03TJ3 Hi,

Thank you for your testing.

In this case Error raised from [`samplecomp.tsx` 11L](https://github.com/L03TJ3/Sample_ExportHOC/blob/cf17d4c553ad04a064619e297605c8a1a8a89f60/src/hoc/samplecomp.tsx#L11). 

Every export statement need name for index.ts file. `export default withTheme()(TestComponent)` statement don't have name. So ctix can't generate export statement. In this case ctix try to use filename for generation like below,

```ts
export { default as samplecomp } from './hoc/samplecomp';
```

How about this?

**Comment by L03TJ3** [comment]
So yes, I agree with the last suggestion.
but if you say that it should take filename for generating index. (or am I reading this wrong, and are you suggesting this?)
As I was thinking that taking the filename would be a rather clean way to solve this
what makes this not working in current version?

**Comment by L03TJ3** [comment]
wait, re-reading it
basically what you state is that taking the filename, or doing the named export is kind of like the same thing... yes?

**Comment by imjuni** [comment]
@L03TJ3 Hi,

Sorry about ambiguity.

1. ctix offer auto naming for about non-named export
    * eg. anonymous arrow function
2. I add auto naming logic for CallExpression, NewExpression (samplecomp.tsx is CallExpression)
3. You can choice auto naming (use filename) or named export

I release new version of ctix 10/30~10/31 KST. Thank you!

**Comment by L03TJ3** [comment]
Thanks to you as well!

**Comment by imjuni** [comment]
@L03TJ3 Hi, 

I release `v1.5.3` - #59 .

Thank you :)
