### ISSUE TITLE
Ignoring exports based on glob pattern

### ISSUE THREAD

**Issue by wejrox** [imjuni/ctix#61]
# Overview 

Big fan of this library, it's made it so much easier to generate type definitions for my package! Just having some teething issues...

I am trying to limit which exports can come out of a file based on export name glob matching, but all the exports are still being generated. 

I don't want to write each entry out because my end goal is to ignore any exports down the file structure matching the pattern, as they're generated files with a similar structure.

# Example

With this configuration
`.ctignore`
```json5
{
  "src/protobufs/*": [
    "*ToJSON",
    "*FromJSON"
  ]
}
```

`.ctirc`
```json5
{
  // common configuration
  // tsconfig.json path: must be specified a path qualifier, such as "./tsconfig.json".
  // Relative to `package.json` directory of the package being built.
  "project": "./tsconfig.json",
  // Export filename: if blank uses "index.ts" or "index.d.ts"
  "exportFilename": "index.ts",
  // [create, single] command configuration
  // Whether to end lines with semicolons
  "useSemicolon": true,
  // Whether to append a timestamp to the right of the ctix comment
  // Only works if the 'useComment' option is set to 'true'
  "useTimestamp": false,
  // Whether to add a comment at first line of created index.ts file informing that it's generated by ctix
  "useComment": false,
  // Symbol to use for quoting strings (quotation mark " or ')
  "quote": "'",
  // Whether to overwrite the exported file (creates a backup)
  "overwrite": true,
  // Whether to remove the backup generated when 'overwrite' is enabled
  "noBackup": true,
  // Whether to retain the file extension specified in the export path
  "keepFileExt": false,
  // [create] command configuration
  // Whether to skip generating index files for empty directories
  "skipEmptyDir": true,
  // [single] command configuration
  // Directory to output the generated index file into
  "output": "./src/",
  // Whether to respect the rootDir or rootDirs configuration in tsconfig.json.
  "useRootDir": false,
  // [remove] command configuration
  // Whether to remove any backup file(s) alongside the generated index file(s)
  "includeBackup": false
}
```

Using the command

```sh
ctix single -c .ctirc
```

Given the following file, I would presume that the `*Model` would still be exported, but the `*ToJSON` and `*FromJSON` would not be.

`src/protobufs/thing/thing_model.ts`
```ts
export enum ThingModel {
  THING_0 = 0,
  THING_1 = 1
}

export function thingModelFromJSON(object: any): ThingModel {
  // <simplified for brevity>
  return 0;
}

export function thingModelToJSON(object: ThingModel): string {
  // <simplified for brevity>
  return "";
}
```

However, the resultant type still contains everything. 

```ts
export { thingModelFromJSON, thingModelToJSON, ThingModel } from './protobufs/thing/thing_model';
```

If I don't use glob pattern matching, it works, but I have a number of `*ToJSON` etc exports which I want to exclude down the file structure

# Why is this important?

1. There is `*` pattern matching already, but there doesn't seem to be support for partial glob patterns `*Thing` etc which is a logical expectation.
2. Users of the library may have huge codebases which it would be impractical to maintain the list of ignored files for, without this change.

**Comment by imjuni** [comment]
@wejrox Thank you for your feedback! Can you create reproducible repo?
