### ISSUE TITLE
ctix fails when source file contains two exports to the same wildcard module declaration

### ISSUE THREAD

**Issue by insidewhy** [imjuni/ctix#62]
Take this code which is typical for a project built with `webpack`:

```typescript
/// <reference path="./DeclareTtfModule.d.ts" />
import RobotoBold from "./fonts/Roboto-Bold.ttf";
import Roboto from "./fonts/Roboto-Regular.ttf";

export { RobotoBold, Roboto };
```

and where `DeclareTtfModule.d.ts` looks like:

```typescript
declare module "*.ttf";
```

Trying to compile a project like this exits with a non-zero status code and with the same error reported identically four times against the final line:

```
> detect same name of export statement: ""*.ttf""
```

Changing the final line so it only exports a single symbol works fine:

```typescript
/// <reference path="./DeclareTtfModule.d.ts" />
import RobotoBold from "./fonts/Roboto-Bold.ttf";
import Roboto from "./fonts/Roboto-Regular.ttf";

export { RobotoBold }
```

Fixed this issue in https://github.com/imjuni/ctix/pull/64

**Comment by imjuni** [comment]
@insidewhy Hi,

Thank you for your contribution!

I've improved your contribution a little bit. I think use compiler api that more accuracy for each situation.

[as-is](https://github.com/imjuni/ctix/blob/186c24cdd8e2f88d89c70fdc1c975647e47a0bbd/src/compilers/getExportInfo.ts#L80) -> 
[to-be](https://github.com/imjuni/ctix/blob/5bced86d444c23d0c3a91925a31c19a21742c5f3/src/compilers/getExportInfo.ts#L83)

In this case, TypeScript Compiler API return `module declaration` node instance. And `module declaration` node return glob pattern applied name.

eg. Friend > *.ttf

So I module declaration node change that return export declaration key. It make information like that,

```json
{
  identifier: 'Friend',
  isIsolatedModules: false,
  moduleDeclaration: "'*.ttf'",
},
```

This improvement can remove the need to change the duplicate detection code. If you agree with this change, I will release the next version in this state.

**Comment by insidewhy** [comment]
> This improvement can remove the need to change the duplicate detection code. If you agree with this change, I will release the next version in this state.

I wanted to do that also, couldn't find a way to do it without changing a lot of other code. From getExported to getExport...

**Comment by imjuni** [comment]
@insidewhy Thank you for your kindness.

I completly agree changing only on validation logic. But I think that exportInfo result less about for validation. But I think the 'exportInfo' function doesn't return information to do the right validation.

Thank you for your feedback! I will release this version soon!

**Comment by insidewhy** [comment]
Thanks for releasing the fix so quickly.
