### ISSUE TITLE
useRootDir unexpected behavior

### ISSUE THREAD

**Issue by benjamin658** [imjuni/ctix#7]
Hi,

I was trying to create a single index.ts by the command `npx ctix single -p ./tsconfig.json --useRootDir`,
the index.ts is created, however, all export statements have the rootDir prefix path.

![截圖 2022-01-20 下午12 06 09](https://user-images.githubusercontent.com/4233028/150271440-91ef129c-8538-4df1-8eff-bc154886c8a5.png)

**Comment by imjuni** [comment]
@benjamin658 Hi,

Thank you for your feedback. I understand your problem and I fixing it. 

Thank you.

**Comment by imjuni** [comment]
@benjamin658 Hi,

I fix this issue in 0.4.5. Thank you!
