### ISSUE TITLE
CtixReasoner outputs empty strings to stderr when there are no true errors

### ISSUE THREAD

**Issue by jR1P621** [imjuni/ctix#79]
The CtixReasoner class arbitrarily calls `this.#streamWrite('');` in several places.  This causes false positives when ctix is called from tools that rely on stderr to determine error state.

**Comment by imjuni** [comment]
Hi @jR1P621 

Would you create reproducable repo?

**Comment by imjuni** [comment]
`CtixReasoner` default option is to use `stderr`, but this can be changed using CLI options. The `reasonerStream` and `progressStream` options can be used to change the stream to output messages to.

**Comment by imjuni** [comment]
@jR1P621 Hi, 

I've working on `ctix` 2.x. In the 2.x version, `Reasoner` will not disply error messages multiple times and will not call `console.error` multiple times to print `\n`. Thank you for your feedback in improving `ctix`.

**Comment by imjuni** [comment]
fixed in `v2.0.0`
