### ISSUE TITLE
Inline ignore for files

### ISSUE THREAD

**Issue by hallister** [imjuni/ctix#80]
Our use-case is a large lerna mono-repo with a number of packages each generating nested index files. Although ctix already provides .ctixignore, it would be extremely handy if we could indicate at the top of a file to ignore exporting it in the generated index:

`/* ctix ignore */`

There may be a use-case for being able to embed this at the export level (if you have files with multiple exports and some should be in the index and others shouldn't), but I think a simple one-off directive at the top of a file is probably "good enough". Curious what the feasibility of a feature like this is, and if the use-case seems broad enough to support it.

**Comment by imjuni** [comment]
@hallister, That's good idea. However, I'm working on another project right now, os I can't update right now. If you issue a PR, I can review it. Thank you for your feedback!

**Comment by imjuni** [comment]
@hallister Hi,

I was working on `ctix` 2.x. The 2.x version now allows you to set include, exclude directly without using the `.ctiignore` file, or use the include, exclude in the `tsconfig.json` file. I was also made improvements to allow you to exclude files or export statements with comments you've suggested. 

Please see the [documentation](https://github.com/imjuni/ctix/blob/master/doc/IN_DEPTH_IGNORE.md#inline-ignore-in-document-comment) I was put together on inline exclude. Barring any special bugs, I will be releasing version 2.x next week. Thank you for your feedback in making `ctix` better.

**Comment by imjuni** [comment]
That feature was added in version 2.0
