### ISSUE TITLE
including ts and tsx files but exclude .d.ts and .stories.tsx files

### ISSUE THREAD

**Issue by simpel** [imjuni/ctix#96]
Hi!

I guess the title says it all, how can I exclude my storybook  and .d.ts files from the barrel file?

**Comment by imjuni** [comment]
See this, https://github.com/imjuni/ctix/blob/master/doc/IN_DEPTH_EXCLUDE.md

Set the exclude field in your options file, or add the `@ctix-exclude` comment to the top of your file
